package proyecto_1;

public class Proyecto_1 {

    public static void main(String[] args) {
        RestList restaurants = new RestList();
        RestNode rest1 = new RestNode();
        rest1.setRestId("A");
        rest1.setRestName("Pizpa");
        FoodList menu1 = new FoodList();
        menu1.addLast("Pizza Margarita");
        menu1.addLast("Pasticho");
        menu1.addLast("Refresco");
        rest1.setMenu(menu1);
        RestNode rest2 = new RestNode();
        rest2.setRestId("B");
        rest2.setRestName("Sotano Siete");
        FoodList menu2 = new FoodList();
        menu2.addLast("Prosciutto Funghi");
        menu2.addLast("Pizza Napoletana");
        menu2.addLast("Calzone");
        rest2.setMenu(menu2);
        RestNode rest3 = new RestNode();
        rest3.setRestId("C");
        rest3.setRestName("Avila Burger");
        FoodList menu3 = new FoodList();
        menu3.addLast("Banquito Burger");
        menu3.addLast("Papas Fritas");
        menu3.addLast("Aros de Cebolla");
        menu3.addLast("Nestea");
        rest3.setMenu(menu3);
        RestNode rest4 = new RestNode();
        rest4.setRestId("D");
        rest4.setRestName("Buffalo Wings");
        FoodList menu4 = new FoodList();
        menu4.addLast("Papitas Kardashian");
        menu4.addLast("Burger Homero");
        menu4.addLast("Costillas");
        menu4.addLast("Agua");
        rest4.setMenu(menu4);
        RestNode rest5 = new RestNode();
        rest5.setRestId("E");
        rest5.setRestName("Holy Chicken");
        FoodList menu5 = new FoodList();
        menu5.addLast("Holy Chicken");
        menu5.addLast("Holy Tempeh");
        menu5.addLast("Holy Slaw");
        menu5.addLast("Holy Chicken Tenders");
        rest5.setMenu(menu5);
        restaurants.addLast(rest1);
        restaurants.addLast(rest2);
        restaurants.addLast(rest3);
        restaurants.addLast(rest4);
        restaurants.addLast(rest5);
        ClientsList clients = new ClientsList();
        ClientNode client1 = new ClientNode("1", "Pepe", "Gonzalez", 234354);
        ClientNode client2 = new ClientNode("2", "Stephania", "Cominos", 24574354);
        ClientNode client3 = new ClientNode("3", "Andrea", "Stanislao", 27385643);
        ClientNode client4 = new ClientNode("4", "Josefina", "La Sifrina", 6547584);
        ClientNode client5 = new ClientNode("5", "Rosa", "Mosa", 574543);
        ClientNode client6 = new ClientNode("6", "Eduardo", "Petardo", 4326534);
        ClientNode client7 = new ClientNode("7", "Enrique", "Manrique", 434543);
        clients.addLast(client1);
        clients.addLast(client2);
        clients.addLast(client3);
        clients.addLast(client4);
        clients.addLast(client5);
        clients.addLast(client6);
        clients.addLast(client7);
        RouteList routeList = new RouteList();
        RouteNode route1 = new RouteNode("A", "1", 3);
        RouteNode route2 = new RouteNode("A", "2", 2);
        RouteNode route3 = new RouteNode("1", "C", 2);
        RouteNode route4 = new RouteNode("1", "5", 8);
        RouteNode route5 = new RouteNode("2", "E", 2);
        RouteNode route6 = new RouteNode("2", "4", 4);
        RouteNode route7 = new RouteNode("C", "5", 3);
        RouteNode route8 = new RouteNode("4", "3", 2);
        RouteNode route9 = new RouteNode("4", "B", 6);
        RouteNode route10 = new RouteNode("5", "B", 3);
        RouteNode route11 = new RouteNode("5", "E", 7);
        RouteNode route12 = new RouteNode("B", "6", 7);
        RouteNode route13 = new RouteNode("3", "7", 1);
        RouteNode route14 = new RouteNode("7", "D", 4);
        RouteNode route15 = new RouteNode("D", "B", 1);
        RouteNode route16 = new RouteNode("D", "6", 5);
        RouteNode route17 = new RouteNode("6", "5", 5);
        RouteNode route18 = new RouteNode("6", "C", 6);
        RouteNode route19 = new RouteNode("E", "1", 1);
        RouteNode route20 = new RouteNode("E", "A", 1);
        routeList.addFirst(route1);
        routeList.addLast(route2);
        routeList.addLast(route3);
        routeList.addLast(route4);
        routeList.addLast(route5);
        routeList.addLast(route6);
        routeList.addLast(route7);
        routeList.addLast(route8);
        routeList.addLast(route9);
        routeList.addLast(route10);
        routeList.addLast(route11);
        routeList.addLast(route12);
        routeList.addLast(route13);
        routeList.addLast(route14);
        routeList.addLast(route15);
        routeList.addLast(route16);
        routeList.addLast(route17);
        routeList.addLast(route18);
        routeList.addLast(route19);
        routeList.addLast(route20);
        Functions f = new Functions();
        RouteList copyRoutes = f.copyRoutes(routeList);
        f.changeRoutesEntrance(routeList, clients);
        f.changeRoutesExits(routeList, clients);
//        DijkstraAlg dijkstra = new DijkstraAlg();
//        PathNode result = dijkstra.runAlgorithm("A", copyRoutes, "6");
//        System.out.println(result.getDistance());
//        result.printVertexes();
//        System.out.println("");
//        routeList.printRoutes();
//        Matrix adjMatrix = new Matrix(restaurants.getSize()+clients.getSize(), 
//                9999);
//        f.fillMatrix(adjMatrix, routeList);
//        adjMatrix.fillDiagonal();
//        adjMatrix.printMatrix();
//        FloydWarshall fl = new FloydWarshall();
//        fl.runFloydWarshall(adjMatrix);
    }
    
}
