package proyecto_1;

public class Proyecto_1 {

    public static void main(String[] args) {
        RouteList routeList = new RouteList();
        RouteNode route1 = new RouteNode("A", "1", 3);
        RouteNode route2 = new RouteNode("A", "2", 2);
        RouteNode route3 = new RouteNode("1", "C", 2);
        RouteNode route4 = new RouteNode("1", "5", 8);
        RouteNode route5 = new RouteNode("2", "E", 2);
        RouteNode route6 = new RouteNode("2", "4", 4);
        RouteNode route7 = new RouteNode("C", "5", 3);
        RouteNode route8 = new RouteNode("4", "3", 2);
        RouteNode route9 = new RouteNode("4", "B", 6);
        RouteNode route10 = new RouteNode("5", "B", 3);
        RouteNode route11 = new RouteNode("5", "E", 7);
        RouteNode route12 = new RouteNode("B", "6", 7);
        RouteNode route13 = new RouteNode("3", "7", 1);
        RouteNode route14 = new RouteNode("7", "D", 4);
        RouteNode route15 = new RouteNode("D", "B", 1);
        RouteNode route16 = new RouteNode("D", "6", 5);
        RouteNode route17 = new RouteNode("6", "5", 5);
        RouteNode route18 = new RouteNode("6", "C", 6);
        RouteNode route19 = new RouteNode("E", "1", 1);
        RouteNode route20 = new RouteNode("E", "A", 1);
        routeList.addFirst(route1);
        routeList.addLast(route2);
        routeList.addLast(route3);
        routeList.addLast(route4);
        routeList.addLast(route5);
        routeList.addLast(route6);
        routeList.addLast(route7);
        routeList.addLast(route8);
        routeList.addLast(route9);
        routeList.addLast(route10);
        routeList.addLast(route11);
        routeList.addLast(route12);
        routeList.addLast(route13);
        routeList.addLast(route14);
        routeList.addLast(route15);
        routeList.addLast(route16);
        routeList.addLast(route17);
        routeList.addLast(route18);
        routeList.addLast(route19);
        routeList.addLast(route20);
        Functions f = new Functions();
        f.changeRoutesEntrance(routeList);
        f.changeRoutesExits(routeList);
        Matrix adjMatrix = new Matrix(12);
        f.fillMatrix(adjMatrix, routeList);
        adjMatrix.fillDiagonal();
        adjMatrix.printMatrix();
//        RestList newList = new RestList();
//        RestNode pizpa = new RestNode();
//        pizpa.setRestId("A");
//        pizpa.setRestName("Pizpa");
//        FoodList menu = new FoodList();
//        menu.addLast("Pasticho");
//        menu.addLast("Pizza");
//        pizpa.setMenu(menu);
//        newList.addLast(pizpa);
//        RestNode sotano7 = new RestNode();
//        sotano7.setRestId("B");
//        sotano7.setRestName("Sotano 7");
//        FoodList sotano7menu = new FoodList();
//        sotano7menu.addLast("Prosciutto Funghi");
//        sotano7menu.addLast("Pizza Napoletana");
//        sotano7menu.addLast("Calzone");
//        sotano7.setMenu(sotano7menu);
//        newList.addLast(sotano7);
//        newList.printNamesMenu();
//        ClientsList clients = new ClientsList();
//        ClientNode test1 = new ClientNode();
//        test1.setId("1");
//        test1.setName("Pepe");
//        test1.setLastName("Gonzalez");
//        test1.setDni(24574354);
//        clients.addLast(test1);
//        ClientNode test2 = new ClientNode();
//        test2.setId("2");
//        test2.setName("Stephania");
//        test2.setLastName("Caminos");
//        test2.setDni(27385643);
//        clients.addLast(test2);
//        clients.printClientsInfo();
    }
    
}
